# Generated by Django 5.2.7 on 2025-11-06 14:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Default annual interest rate (in %)', max_digits=5)),
                ('late_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Late fee percentage charged on overdue payments', max_digits=5)),
                ('grace_period_days', models.PositiveIntegerField(default=10, help_text='Number of days allowed before late fee applies')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Settings',
                'verbose_name_plural': 'Bank Settings',
            },
        ),
    ]
