# Generated by Django 5.2.7 on 2025-11-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_banksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpaymentschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
